export const filterKey = {
  HitLevel: 'hitLevel',
  BlockFrameMin: 'blockFrameMin',
  BlockFrameMax: 'blockFrameMax',
  HitFrameMin: 'hitFrameMin',
  HitFrameMax: 'hitFrameMax',
  NumHitsMin: 'numHitsMin',
  NumHitsMax: 'numHitsMax',
  HeatEngager: 'heatEngager',
  Homing: 'homing',
  BalconyBreak: 'balconyBreak',
  Tornado: 'tonrnado',
  Jails: 'jails',
  Chip: 'chip',
  HighCrush: 'cs',
  LowCrush: 'js',
  PowerCrush: 'pc',
  Spike: 'spk',
  FloorBreak: 'fbr',
  Knee: 'kne',
  Elbow: 'elb',
  Weapon: 'wpn',
  Stance: 'stance',
  WallCrush: 'wc',
  Video: 'video',
  HitsGrounded: 'hitsGrounded',
  RemoveRecoveryHealth: 'removeRecoveryHealth',
} as const

export const hitLevelValue = {
  Low: 'l',
  Mid: 'm',
  High: 'h',
  Throw: 't',
} as const
