name: Unit Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    name: 'Running Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: npm install

      - name: 'Running unit tests'
        run: npm run test

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Running python unit tests'
        run: python -m unittest discover -s utils
