name: Unit Testing 

on:
  push:
    paths:
      - "src/**"
      - "package.json"

jobs:
  typecheck:
    name: "Running Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: npm install
        
      - name: "Running unit tests"
        run: npm run test