export type TableId =
  | 'frames_normal'
  | 'frames_tenhit'
  | 'frames_throws'
  | 'key_moves'
  | 'punishers_standing'
  | 'punishers_crouching'
  | 'punishers_whiff'
  | 'combos_normal'
  | 'combos_beginner'
  | 'combos_small'
  | 'combos_ender'
  | 'combos_wall'
  | 'videos_match'
